FROM node:18

# Create app directory
WORKDIR /app

# Create frontend directory
RUN mkdir frontend

# Set working directory for frontend
WORKDIR /app/frontend

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose the port
EXPOSE 3000

# Copy the rest of the frontend code
COPY . .

# Start the frontend application
CMD ["npm", "run", "dev"]
